const fs = require('fs'); let data = fs.readFileSync('src/app/components/TransformationsSection.js', 'utf8');
data = data.replace('We specialise in<br/>evidence-based nutrition<br/>and elite training protocols.', 'We build real strength<br/>and discipline.<br/>No excuses.');
data = data.replace('Elite Physique<br/><span>/ Transformations</span>', 'Real Results<br/><span>/ No Excuses</span>');
data = data.replace('Based in<br/>the United Kingdom', 'London Based<br/>Training');
data = data.replace(	ext= + '' + Whether you're starting from scratch or breaking through a plateau, we engineer tailored roadmaps that demand results and amplify your physical potential. + '', 	ext= + '' + Whether you are hitting the gym for the first time or stuck on a plateau, we provide the exact training and nutrition protocols you need to grow. No generic advice, just proven methods. + '');
data = data.replace('The Method', 'The Blueprint');
data = data.replace(	ext= + '' + Step into the future of fitness with our proven systems. We provide cutting-edge physical transformations tailored to your lifestyle and driven by science. + '', 	ext= + '' + A physique is built on consistency. We strip away the guesswork with direct coaching, heavy lifting, and nutrition plans that actually work for your daily routine. + '');
data = data.replace('Every rep, every meal,<br/>meticulously calculated<br/>for your body.', 'Strength, performance,<br/>and dedicated<br/>training.');
data = data.replace('Precision Driven<br/><span>/ Methodology</span>', 'Uncompromising<br/><span>/ Standards</span>');
data = data.replace('Science over<br/>guesswork', 'London Based<br/>Coaching');
data = data.replace(	ext= + '' + We don't believe in generic programs. Your biology is unique, and your training roadmap should reflect that uncompromising standard. + '', 	ext= + '' + We don't do cookie-cutter workouts. If you want serious size and definition, you need a plan that forces you to adapt and progress every single session. + '');
data = data.replace('<span>Nutrition</span>', '<span>Strength</span>');
data = data.replace('<span>&rarr; Programming</span>', '<span>&rarr; Nutrition</span>');
data = data.replace('<span>Recovery</span>', '<span>Mindset</span>');
data = data.replace('Uncompromising<br/>Standards', 'Absolute<br/>Discipline');
data = data.replace(	ext= + '' + Beyond just sets and reps, we engineer a complete paradigm shift in your daily habits. Success is built on consistency and relentless refinement. + '', 	ext= + '' + Real transformations require more than just showing up. We demand focus, proper fueling, and the willingness to push past your mental limits. + '');
data = data.replace('A physique that<br/>lasts a lifetime.', 'A physique built<br/>to last.');
data = data.replace('Sustainable<br/><span>/ Results</span>', 'Proven<br/><span>/ Results</span>');
data = data.replace('Peak<br/>Performance', 'Total<br/>Recomposition');
data = data.replace(	ext= + '' + Transformations aren't temporary. We build resilient habits that ensure you retain your peak condition year-round. + '', 	ext= + '' + Fitness isn't a temporary fix. We build resilient habits so you stay in peak condition long after the initial transformation is over. + '');
fs.writeFileSync('src/app/components/TransformationsSection.js', data);
